### PR TITLE
add Silentgear

### LINKED ISSUE #8: [1.14.4] Silentgear
image

### PR DESCRIPTION
**Pull request by MelanX**
close https://github.com/CyanideX/Unity-Dark/issues/8

### CODE REVIEW

**Comment by CyanideX** [comment]
I really appreciate you taking the time to complete all of the suggestions! 🥰 The only issue I have is that some GUI elements were converted when using the PS action that should have remained white.

image

If possible, could you go through the GUIs and manually fix these issues?

**Comment by MelanX** [comment]
It's a bit much work but I could do it. At the moment I'm on changing all the languages files of Mekanism.. I could do it within the next few days

**Comment by CyanideX** [comment]
I know it can be a lot of work but I can't accept the PRs without the changes. 😝

**Comment by MelanX** [comment]
finally fixed the texture :D

**Pull request merged**
